Home Page
krystianKuch22/marcin-front pull request #1
Opened 2024-11-15 21:05 UTC by krystianKuch22

2024-11-15 21:07 UTC, LimbaApp requested changes

2024-11-15 21:07 UTC, LimbaApp commented on components/layout/Header/Header.js
> +            <b>Dobry Terapeuta</b>
Can we move translations to the separate file?

2024-11-15 21:07 UTC, LimbaApp commented on components/sections/HomeSection/HomeSection.js
> +      <Wrapper>
Please move translations

2024-11-24 23:21 UTC, mzglinicki approved these changes

2024-11-24 23:21 UTC, mzglinicki commented on components/common/ButtonLink/ButtonLink.js
> +  bgc,
use background name

2024-12-10 21:16 UTC, merged